name: Hello World

on:
  push:
    branches:
      - main
      - develop
    paths:
      - "hello-world/**"
      - ".github/workflows/hello-world.yml"

jobs:
  say-hello:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./hello-world
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Say hello
        run: echo "Hello, world!"
