name: Minimal test

on:
  push:
    branches:
      - main
    paths:
      - "minimal-test/**"
      - ".github/workflows/minimal-test.yml"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./minimal-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
